### ISSUE TITLE
Awesome app

### ISSUE THREAD

**Issue by wesfox** [mcieno/simple-secret-santa#6]
Hi, 

Just to say that it is an awesome app, heavy but docker cache works well !
I forked it to translate it in French here : https://github.com/wesfox/simple-secret-santa,

Three minor improvment : 

1. You may add a max amount (configurable), I dirty added it on my side.
2. The feature to make the cursor go to the next case when entering the password works on an Ipad (Chrome), a desktop browser (Chrome) but struggle on Android (Chrome)
3. You may catch the "Ctrl + V" input to pass the cached key in the input.

Cheers !

**Comment by mcieno** [comment]
Thank you, glad you liked it!

I've implemented your suggestions (paste, i18n and texts customizability) as well as an improved deployment experience in #7.

'Till next Christmas ;)
